### PR TITLE
Add transformation_depth_image_to_point_cloud

### PR DESCRIPTION
**Pull request by DominikMa**
Sorry if I'm spamming you with pull requests...
I added the conversion to point clouds. For the original depth image and for the to the color camera transformed depth images.
The output looks like expected.

### CODE REVIEW

**Comment by lpasselin** [comment]
Would it be possible to add a simple example for this one?

**Comment by DominikMa** [comment]
Sorry I was on vacation. What kind of example do you want? Just any image together with its plotted point cloud?

**Comment by lpasselin** [comment]
I meant a python script to add to the example directory

**Comment by lpasselin** [comment]
I made a mistake merging develop into this branch. I will fix this problem.

**Comment by lpasselin** [comment]
https://github.com/etiennedub/pyk4a/pull/58

**Pull request closed without merging**
