### PR TITLE
Calibration: Add functions to access intrinsic camera parameters

### PR DESCRIPTION
**Pull request by johan12345**
Camera matrix and distortion coefficients in OpenCV-compatible format.
These values are already specific to the selected camera resolution (in contrast to those accessed through calibration_raw).

related to #35, #69

### CODE REVIEW

**Comment by lpasselin** [comment]
Thanks for the PR!

If anyone else confirm the new functions work properly? (I will have access to my k4a later this week)

**Comment by ZdenekM** [comment]
I haven't tested the code yet, but it seems correct. I was using [this conversion](https://github.com/robofit/arcor2/blob/85099ef3e1ed42064406962e9350505c8b4d517d/src/python/arcor2_kinect_azure/kinect_azure.py#L63) so far.

**Comment by pgrady3** [comment]
I've downloaded this pull request and can confirm that getting the color camera intrinsic and distortion parameters work. They allow undistorting with the OpenCV functions.

```
k4a = PyK4A(
    Config(
        color_resolution=pyk4a.ColorResolution.RES_1080P,
        depth_mode=pyk4a.DepthMode.WFOV_2X2BINNED,
        synchronized_images_only=False,
        camera_fps=pyk4a.FPS.FPS_15
    ),
)

k4a.start()

intrinsic = k4a.calibration.get_camera_matrix(pyk4a.calibration.CalibrationType.COLOR)
distortion = k4a.calibration.get_distortion_coefficients(pyk4a.calibration.CalibrationType.COLOR)
```

**Comment by wangmiaowei** [comment]
How to undistort the depth map? I just use opencv function but the results are bad
import numpy as np
import cv2
import open3d as o3d
w = 640
h = 576

intrinsic = np.array([[503.08432007, 0.,324.27612305],[  0. ,503.16601562,330.65237427],
 [  0. ,0.  ,1.        ]])
dist_coeffs=np.array([ 2.06184745e-01,-1.28368318e-01,2.92664499e-05,2.75623443e-05,
 -5.74961351e-03,5.43716311e-01,-1.30464926e-01,-3.45068611e-02])

newcameramatrix, _ = cv2.getOptimalNewCameraMatrix(
    intrinsic, dist_coeffs, (w, h), 1, (w, h)
)
path1= "/home/SENSETIME/wangmiaowei/WMW_WORK/programs/2022_start/data_local_center/plant_3D/Pole/cylinder80mm1/depth/SN_1.png"
depth = cv2.imread(path1, cv2.IMREAD_UNCHANGED)
undistorted_image = cv2.undistort(
    depth, intrinsic, dist_coeffs, None, newcameramatrix
)
depth=undistorted_image/1000
print('newcamera: ',newcameramatrix)
depth = o3d.geometry.Image(depth.astype('float32'))
cam = o3d.camera.PinholeCameraIntrinsic()
cam.intrinsic_matrix = intrinsic
pcd = o3d.geometry.PointCloud.create_from_depth_image(depth,cam)
o3d.visualization.draw_geometries([pcd])
o3d.io.write_point_cloud("/home/SENSETIME/wangmiaowei/WMW_WORK/programs/2022_start/data_local_center/plant_3D/Pole/cylinder80mm1/depth/SN_1.ply",pcd)

**Pull request merged**
